/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package telas;

import domain.Cliente;
import dao.ClienteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author dougl
 * @author Pablo
 */
public class MenuPrincipal extends javax.swing.JFrame {
    private domain.Cliente cliente;
    private ClienteDAO clienteDAO;
    
    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal(Cliente cliente, ClienteDAO clienteDAO) {
        this.cliente = cliente;
        this.clienteDAO = clienteDAO;
        initComponents();
        setLocationRelativeTo(null);
        
        if (cliente.getConta() == null) {
            JOptionPane.showMessageDialog(null, "Conta não encontrada para o cliente.", "Erro", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenuBar5 = new javax.swing.JMenuBar();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuBar6 = new javax.swing.JMenuBar();
        jMenu10 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jRadioButtonMenuItem3 = new javax.swing.JRadioButtonMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        verSaldoButton = new javax.swing.JButton();
        depositarButton = new javax.swing.JButton();
        infoButton = new javax.swing.JButton();
        sacarButton = new javax.swing.JButton();
        transferirButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        informacoesMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenu14 = new javax.swing.JMenu();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenu6.setText("File");
        jMenuBar4.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("File");
        jMenuBar5.add(jMenu8);

        jMenu9.setText("Edit");
        jMenuBar5.add(jMenu9);

        jMenu10.setText("File");
        jMenuBar6.add(jMenu10);

        jMenu11.setText("Edit");
        jMenuBar6.add(jMenu11);

        jRadioButtonMenuItem3.setSelected(true);
        jRadioButtonMenuItem3.setText("jRadioButtonMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 102, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(25, 25, 27));
        jPanel1.setForeground(new java.awt.Color(25, 25, 27));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(213, 226, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Menu");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 100, -1));

        verSaldoButton.setBackground(new java.awt.Color(35, 147, 247));
        verSaldoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        verSaldoButton.setForeground(new java.awt.Color(238, 238, 240));
        verSaldoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/saldo 1.png"))); // NOI18N
        verSaldoButton.setText("Ver Saldo");
        verSaldoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verSaldoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(verSaldoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, 40));

        depositarButton.setBackground(new java.awt.Color(35, 147, 247));
        depositarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        depositarButton.setForeground(new java.awt.Color(238, 238, 240));
        depositarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/deposit 1.png"))); // NOI18N
        depositarButton.setText("Depositar");
        depositarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(depositarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 180, 40));

        infoButton.setBackground(new java.awt.Color(35, 147, 247));
        infoButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        infoButton.setForeground(new java.awt.Color(238, 238, 240));
        infoButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/extrato.png"))); // NOI18N
        infoButton.setText("Movimentações da Conta");
        infoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoButtonActionPerformed(evt);
            }
        });
        jPanel1.add(infoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 220, 40));

        sacarButton.setBackground(new java.awt.Color(35, 147, 247));
        sacarButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sacarButton.setForeground(new java.awt.Color(238, 238, 240));
        sacarButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/withdraw 1.png"))); // NOI18N
        sacarButton.setText("Sacar");
        sacarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sacarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(sacarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 180, 40));

        transferirButton.setBackground(new java.awt.Color(35, 147, 247));
        transferirButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        transferirButton.setForeground(new java.awt.Color(238, 238, 240));
        transferirButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transfer 1.png"))); // NOI18N
        transferirButton.setText("Transferir");
        transferirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirButtonActionPerformed(evt);
            }
        });
        jPanel1.add(transferirButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 180, 40));

        jPanel2.setBackground(new java.awt.Color(25, 25, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coin2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 440, 340));

        jMenu2.setText("Opções");

        informacoesMenuItem1.setText("Informações");
        informacoesMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacoesMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(informacoesMenuItem1);

        jMenuItem2.setText("Sobre");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        jMenu2.add(logoutMenuItem);
        jMenu2.add(jSeparator1);

        jMenuBar1.add(jMenu2);

        jMenu14.setText("Informações");
        jMenu14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu14ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu14);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 416, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verSaldoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verSaldoButtonActionPerformed
        // TODO add your handling code here:
        
        //Retorna o saldo do cliente
        JOptionPane.showMessageDialog(null, "Saldo: R$ " + cliente.getConta().getSaldo());
    }//GEN-LAST:event_verSaldoButtonActionPerformed

    private void depositarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarButtonActionPerformed
        // TODO add your handling code here:
        
        //Realiza a operação de depósito
        String valorStr = JOptionPane.showInputDialog("Valor para depositar:");
        double valor = Double.parseDouble(valorStr);
        cliente.getConta().depositar(valor);
        JOptionPane.showMessageDialog(null, "Depósito realizado com sucesso!");
    }//GEN-LAST:event_depositarButtonActionPerformed

    private void sacarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sacarButtonActionPerformed
        // TODO add your handling code here:
        
        //Realiza a operação de saque
        String valorStr = JOptionPane.showInputDialog("Valor para sacar:");
        double valor = Double.parseDouble(valorStr);
        if (cliente.getConta().sacar(valor)) {
            JOptionPane.showMessageDialog(null, "Saque realizado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Saldo insuficiente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_sacarButtonActionPerformed

    private void infoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoButtonActionPerformed
        // TODO add your handling code here:
        
        //Retorna o histórico de transações para o usuário
        StringBuilder historico = new StringBuilder();
        for (domain.Transacao transacao : cliente.getConta().getTransacoes()) {
            historico.append(transacao.toString()).append("\n");
        }
        JOptionPane.showMessageDialog(null, historico.toString());
    }//GEN-LAST:event_infoButtonActionPerformed

    private void transferirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirButtonActionPerformed
        // TODO add your handling code here:
        
        String usernameStr = JOptionPane.showInputDialog("Nome do titular:");        
        // Sai do método se o usuário cancelou
        if (usernameStr == null) {
            return; 
        }
        
        String numContaStr = JOptionPane.showInputDialog("Número da conta de " + usernameStr + ":");        
        // Sai do método se o usuário cancelou
        if (numContaStr == null) { 
            return; 
        } else if (numContaStr.equals(cliente.getNumeroConta())){
            JOptionPane.showMessageDialog(null, "Digite uma conta diferente da sua!", "Erro", JOptionPane.ERROR_MESSAGE);
            numContaStr = JOptionPane.showInputDialog("Número da conta de " + usernameStr + ":");          
        }    
        
        
        String valorStr = JOptionPane.showInputDialog("Valor para transferir:");        
        // Sai do método se o usuário cancelou
        if (valorStr == null) {
            return; 
        }
        
        //Realiza a operação de transferência:
        double valor = Double.parseDouble(valorStr);        
        if(valor <= cliente.getConta().getSaldo()){
            if (cliente.getConta().transferir(usernameStr, numContaStr, valor, clienteDAO)) {
                JOptionPane.showMessageDialog(null, "Transferência realizada com sucesso!");
            } else {
                JOptionPane.showMessageDialog(null, "Conta não encontrada", "Erro", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Saldo insuficiente!", "Erro", JOptionPane.ERROR_MESSAGE);
        }        
    }//GEN-LAST:event_transferirButtonActionPerformed

    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        // TODO add your handling code here:
        TelaLogin telaLogin = new TelaLogin(clienteDAO);
        telaLogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    private void informacoesMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacoesMenuItem1ActionPerformed
        // TODO add your handling code here:
        StringBuilder dados = new StringBuilder();
        dados.append("Nome: ").append(cliente.getNome()).append("\n");
        dados.append("CPF: ").append(cliente.getCpf()).append("\n");
        dados.append("Telefone: ").append(cliente.getTelefone()).append("\n");
        dados.append("Endereço: ").append(cliente.getEndereco()).append("\n");
        dados.append("Numero da conta: ").append(cliente.getNumeroConta()).append("\n");
        JOptionPane.showMessageDialog(null, dados.toString());
    }//GEN-LAST:event_informacoesMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        
        Autores autores = new Autores(clienteDAO, cliente);
        
        autores.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu14ActionPerformed
        // TODO add your handling code here:
        StringBuilder dados = new StringBuilder();
        dados.append("Nome: ").append(cliente.getNome()).append("\n");
        dados.append("CPF: ").append(cliente.getCpf()).append("\n");
        dados.append("Telefone: ").append(cliente.getTelefone()).append("\n");
        dados.append("Endereço: ").append(cliente.getEndereco()).append("\n");
        dados.append("Numero da conta: ").append(cliente.getNumeroConta()).append("\n");
        JOptionPane.showMessageDialog(null, dados.toString());
    }//GEN-LAST:event_jMenu14ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton depositarButton;
    private javax.swing.JButton infoButton;
    private javax.swing.JMenuItem informacoesMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuBar jMenuBar5;
    private javax.swing.JMenuBar jMenuBar6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem logoutMenuItem;
    private javax.swing.JButton sacarButton;
    private javax.swing.JButton transferirButton;
    private javax.swing.JButton verSaldoButton;
    // End of variables declaration//GEN-END:variables
}
